import type { BrowserEvent } from './api';

/** Local-only events generated by the UI (not from the server) */
export interface LocalConnectedEvent {
  type: 'daemon:connected';
}

export interface LocalDisconnectedEvent {
  type: 'daemon:disconnected';
}

/** Union of server events and local UI-generated connection events */
export type DaemonEvent = BrowserEvent | LocalConnectedEvent | LocalDisconnectedEvent;
